pluginManagement {
    repositories {
        maven { url = "https://maven.fabricmc.net/" }
        gradlePluginPortal()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        maven { url = "https://maven.fabricmc.net/" }
        maven {
            name = "Mojang Libraries"
            url = "https://libraries.minecraft.net/"
            metadataSources {
                artifact()
            }
        }
        mavenCentral()
    }
}
rootProject.name = "AutoAnvil"
